require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DisponibilitesController do

  # This should return the minimal set of attributes required to create a valid
  # Disponibilite. As you add validations to Disponibilite, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "id_utilisateur" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DisponibilitesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all disponibilites as @disponibilites" do
      disponibilite = Disponibilite.create! valid_attributes
      get :index, {}, valid_session
      assigns(:disponibilites).should eq([disponibilite])
    end
  end

  describe "GET show" do
    it "assigns the requested disponibilite as @disponibilite" do
      disponibilite = Disponibilite.create! valid_attributes
      get :show, {:id => disponibilite.to_param}, valid_session
      assigns(:disponibilite).should eq(disponibilite)
    end
  end

  describe "GET new" do
    it "assigns a new disponibilite as @disponibilite" do
      get :new, {}, valid_session
      assigns(:disponibilite).should be_a_new(Disponibilite)
    end
  end

  describe "GET edit" do
    it "assigns the requested disponibilite as @disponibilite" do
      disponibilite = Disponibilite.create! valid_attributes
      get :edit, {:id => disponibilite.to_param}, valid_session
      assigns(:disponibilite).should eq(disponibilite)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Disponibilite" do
        expect {
          post :create, {:disponibilite => valid_attributes}, valid_session
        }.to change(Disponibilite, :count).by(1)
      end

      it "assigns a newly created disponibilite as @disponibilite" do
        post :create, {:disponibilite => valid_attributes}, valid_session
        assigns(:disponibilite).should be_a(Disponibilite)
        assigns(:disponibilite).should be_persisted
      end

      it "redirects to the created disponibilite" do
        post :create, {:disponibilite => valid_attributes}, valid_session
        response.should redirect_to(Disponibilite.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved disponibilite as @disponibilite" do
        # Trigger the behavior that occurs when invalid params are submitted
        Disponibilite.any_instance.stub(:save).and_return(false)
        post :create, {:disponibilite => { "id_utilisateur" => "invalid value" }}, valid_session
        assigns(:disponibilite).should be_a_new(Disponibilite)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Disponibilite.any_instance.stub(:save).and_return(false)
        post :create, {:disponibilite => { "id_utilisateur" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested disponibilite" do
        disponibilite = Disponibilite.create! valid_attributes
        # Assuming there are no other disponibilites in the database, this
        # specifies that the Disponibilite created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Disponibilite.any_instance.should_receive(:update_attributes).with({ "id_utilisateur" => "1" })
        put :update, {:id => disponibilite.to_param, :disponibilite => { "id_utilisateur" => "1" }}, valid_session
      end

      it "assigns the requested disponibilite as @disponibilite" do
        disponibilite = Disponibilite.create! valid_attributes
        put :update, {:id => disponibilite.to_param, :disponibilite => valid_attributes}, valid_session
        assigns(:disponibilite).should eq(disponibilite)
      end

      it "redirects to the disponibilite" do
        disponibilite = Disponibilite.create! valid_attributes
        put :update, {:id => disponibilite.to_param, :disponibilite => valid_attributes}, valid_session
        response.should redirect_to(disponibilite)
      end
    end

    describe "with invalid params" do
      it "assigns the disponibilite as @disponibilite" do
        disponibilite = Disponibilite.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Disponibilite.any_instance.stub(:save).and_return(false)
        put :update, {:id => disponibilite.to_param, :disponibilite => { "id_utilisateur" => "invalid value" }}, valid_session
        assigns(:disponibilite).should eq(disponibilite)
      end

      it "re-renders the 'edit' template" do
        disponibilite = Disponibilite.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Disponibilite.any_instance.stub(:save).and_return(false)
        put :update, {:id => disponibilite.to_param, :disponibilite => { "id_utilisateur" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested disponibilite" do
      disponibilite = Disponibilite.create! valid_attributes
      expect {
        delete :destroy, {:id => disponibilite.to_param}, valid_session
      }.to change(Disponibilite, :count).by(-1)
    end

    it "redirects to the disponibilites list" do
      disponibilite = Disponibilite.create! valid_attributes
      delete :destroy, {:id => disponibilite.to_param}, valid_session
      response.should redirect_to(disponibilites_url)
    end
  end

end
