require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UtilisateursController do

  # This should return the minimal set of attributes required to create a valid
  # Utilisateur. As you add validations to Utilisateur, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "nom" => "MyString",
      "prenom" => "MyString"}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UtilisateursController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all utilisateurs as @utilisateurs" do
      utilisateur = Utilisateur.create! valid_attributes
      get :index, {}, valid_session
      assigns(:utilisateurs).should eq([utilisateur])
    end
  end

  describe "GET show" do
    it "assigns the requested utilisateur as @utilisateur" do
      utilisateur = Utilisateur.create! valid_attributes
      get :show, {:id => utilisateur.to_param}, valid_session
      assigns(:utilisateur).should eq(utilisateur)
    end
  end

  describe "GET new" do
    it "assigns a new utilisateur as @utilisateur" do
      get :new, {}, valid_session
      assigns(:utilisateur).should be_a_new(Utilisateur)
    end
  end

  describe "GET edit" do
    it "assigns the requested utilisateur as @utilisateur" do
      utilisateur = Utilisateur.create! valid_attributes
      get :edit, {:id => utilisateur.to_param}, valid_session
      assigns(:utilisateur).should eq(utilisateur)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Utilisateur" do
        expect {
          post :create, {:utilisateur => valid_attributes}, valid_session
        }.to change(Utilisateur, :count).by(1)
      end

      it "assigns a newly created utilisateur as @utilisateur" do
        post :create, {:utilisateur => valid_attributes}, valid_session
        assigns(:utilisateur).should be_a(Utilisateur)
        assigns(:utilisateur).should be_persisted
      end

      it "redirects to the created utilisateur" do
        post :create, {:utilisateur => valid_attributes}, valid_session
        response.should redirect_to(Utilisateur.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved utilisateur as @utilisateur" do
        # Trigger the behavior that occurs when invalid params are submitted
        Utilisateur.any_instance.stub(:save).and_return(false)
        post :create, {:utilisateur => { "nom" => "invalid value" }}, valid_session
        assigns(:utilisateur).should be_a_new(Utilisateur)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Utilisateur.any_instance.stub(:save).and_return(false)
        post :create, {:utilisateur => { "nom" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested utilisateur" do
        utilisateur = Utilisateur.create! valid_attributes
        # Assuming there are no other utilisateurs in the database, this
        # specifies that the Utilisateur created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Utilisateur.any_instance.should_receive(:update_attributes).with({ "nom" => "MyString" })
        put :update, {:id => utilisateur.to_param, :utilisateur => { "nom" => "MyString" }}, valid_session
      end

      it "assigns the requested utilisateur as @utilisateur" do
        utilisateur = Utilisateur.create! valid_attributes
        put :update, {:id => utilisateur.to_param, :utilisateur => valid_attributes}, valid_session
        assigns(:utilisateur).should eq(utilisateur)
      end

      it "redirects to the utilisateur" do
        utilisateur = Utilisateur.create! valid_attributes
        put :update, {:id => utilisateur.to_param, :utilisateur => valid_attributes}, valid_session
        response.should redirect_to(utilisateur)
      end
    end

    describe "with invalid params" do
      it "assigns the utilisateur as @utilisateur" do
        utilisateur = Utilisateur.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Utilisateur.any_instance.stub(:save).and_return(false)
        put :update, {:id => utilisateur.to_param, :utilisateur => { "nom" => "invalid value" }}, valid_session
        assigns(:utilisateur).should eq(utilisateur)
      end

      it "re-renders the 'edit' template" do
        utilisateur = Utilisateur.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Utilisateur.any_instance.stub(:save).and_return(false)
        put :update, {:id => utilisateur.to_param, :utilisateur => { "nom" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested utilisateur" do
      utilisateur = Utilisateur.create! valid_attributes
      expect {
        delete :destroy, {:id => utilisateur.to_param}, valid_session
      }.to change(Utilisateur, :count).by(-1)
    end

    it "redirects to the utilisateurs list" do
      utilisateur = Utilisateur.create! valid_attributes
      delete :destroy, {:id => utilisateur.to_param}, valid_session
      response.should redirect_to(utilisateurs_url)
    end
  end

end
